name: macro_sandbox
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-152

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  json: ^0.20.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
